### ISSUE TITLE
Can not install topocalc

### ISSUE THREAD

**Issue by charalamm** [USDA-ARS-NWRC/topocalc#15]
* topocalc version: >= 3.0.0
* Python version: >= 3.10
* Operating System: linux debian

### Description

I am trying to install topocalc in a virtual environment but I get the following error:
```
Collecting topocalc
  Using cached topocalc-0.5.0.tar.gz (7.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/user/Projects/Project/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/Projects/Project/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/Projects/Project/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-l7yq1pm7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-l7yq1pm7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-l7yq1pm7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-l7yq1pm7/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 5, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### What I Did

The error above was produced with all following virtual environments:
* Virtual environments with venv in python 3.10
* Virtual environments with venv in python 3.11
* Virtual environments with venv in python 3.12
* Virtual environments with uv in python 3.11
* Virtual environments with uv in python 3.12

I have tried installing numpy prior to installing topocalc but it does not work

**Comment by Hedrick-ARS** [comment]
Hello. The last python version that topocalc was developed on was 3.7. We are not in an active development mode for this at the moment, so I'd suggest building your virtual environment with 3.7. The error you're seeing could be due to the version of wheel (v0.33.6), but I'm only guessing at this point.
